name = "ExampleNew"
uuid = "726d3906-2c5c-46bf-a75b-baaffaf98106"
authors = ["suyash"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
